### ISSUE TITLE
Tech Stack Evaluation

### ISSUE THREAD

**Issue by JohnWebster1** [JohnWebster1/JIA-2323-BarIQ#9]
Develop the pros and cons of specific technologies and detail the choices that we made

**Comment by bobbybleu** [comment]
Evaluation of technologies for Front-End Web: ReactJS
Pros: Offers extensive and enriched library giving more flexibility to developers
          Scope for testing applications is extremely easy
Cons: React only covers UI layers of the app

Evaluation of technologies for Back-End: Firebase
Pros: Firebase offers methods of authentication which would help with how we might track users
         Concise documentation to help developers unfamiliar with Firebase
Cons: Android centered 
           Less support for iOS is offered

Evaluation of technologies for Database: Firestore
Pros: Works well with Flutter which we are using for our cloud platform
          Offers offline capabilities for developers
          Viable backend option for “minor” user-focused apps	
Cons: Querying in Firestore can be a bit complex despite it being so powerful
           Data migration is tricky when working with future versions of the application

Evaluation of technologies for Cloud Platform: Flutter
Pros: Enables developers to make instant changes in the application great for fixing bugs!
         Flutter-based apps are smooth in performance
Cons: Not a lot of resources to query from because it has not been around long enough so we                                                                        	 must make everything from scratch
	We have to learn Dart to work with Flutter
